service:
 name: relate-gram-ok

plugins:
 - serverless-webpack
#  - serverless-plugin-optimize
 - serverless-offline

provider:
 name: aws
 runtime: nodejs12.x

functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: lambdas/handler.handler
   events:
     - http:
         method: any
         path: /{any+}

custom:
  webpack:
    webpackConfig: 'serverless-webpack.config.js'   # Name of webpack configuration file